version: '3.9'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - db-data:/data/db
  redisdb:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t8
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
